# **Numpy** 

Esta biblioteca, cuyo nombre significa numerical Python, constituye el núcleo de muchas otras bibliotecas de Python que se han originado a partir de ella. De hecho, NumPy es la biblioteca básica para la computación científica en Python, ya que proporciona estructuras de datos y funciones de alto rendimiento que el paquete básico de Python no proporciona.

NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

## Importar la libreria NumPy

In [29]:
import numpy as np 

In [31]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [4]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [6]:
from math import sin
seno = []
for i in [1,2,3]:
    seno.append(sin(i))
seno

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [7]:
[sin(i) for i in [1,2,3]]

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [8]:
x = np.array([[1,2,3], [4,5,6]])
x.shape

(2, 3)

In [14]:
y = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
y[0, :]

array([1, 2, 3, 4])

In [23]:
for i in [0,1,2]:
    print(y[i, :])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [28]:
for j in [0,1,2,3]:
    print(y[:, j])

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]


In [39]:
y[: , 1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [54]:
y[: , ::-2]

array([[ 4,  2],
       [ 8,  6],
       [12, 10]])

## **Creación intrinseca de arreglos**

La biblioteca NumPy proporciona un conjunto de funciones que generan ndarrays con contenido inicial, creados con diferentes valores según la función.



In [65]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [73]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [71]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [77]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [80]:
np.random.random(3)

array([0.10229284, 0.2612804 , 0.88170822])

In [83]:
np.random.random((5,4))

array([[0.05699632, 0.54328886, 0.36825803, 0.04971626],
       [0.76103404, 0.55572633, 0.73934728, 0.80623831],
       [0.12952726, 0.50931806, 0.47501145, 0.28420002],
       [0.9792229 , 0.04558053, 0.46451453, 0.61734159],
       [0.08833912, 0.86656396, 0.07813913, 0.064129  ]])

## **Operaciones básicas**

In [95]:
a = np.arange(0,4)
a

array([0, 1, 2, 3])

In [90]:
a+4

array([4, 5, 6, 7])

In [103]:
2*a

array([0, 2, 4, 6])

In [111]:
A = np.matrix(np.arange(0,12).reshape(3,4))
B = np.matrix(np.arange(12,24).reshape(4,3))


In [112]:
np.dot(A,B)

matrix([[114, 120, 126],
        [378, 400, 422],
        [642, 680, 718]])

In [117]:
np.dot(B,A)

matrix([[164, 203, 242, 281],
        [200, 248, 296, 344],
        [236, 293, 350, 407],
        [272, 338, 404, 470]])

In [115]:
a = np.arange(0,12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
b*a

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [116]:
a*b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])


## **Funciones universales**

In [119]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [120]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [121]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [125]:
np.cos(a)

array([ 1.38177329,  0.49315059, -0.84887249, -1.41044612, -0.67526209])

## **Agregar funciones**

In [138]:
a = 5*np.random.random(5)+1
a

array([4.66957913, 1.56881419, 1.53548605, 5.58621441, 1.93746405])

In [139]:
a.min(), a.max(), a.sum(), a.mean(), a.std()

(1.535486052374539,
 5.58621440976999,
 15.297557828177112,
 3.0595115656354226,
 1.7193235812259469)

## **Indexando**

In [141]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [144]:
a[4], a[-1], a[0],a[-6]

(14, 15, 10, 10)

In [145]:
a[[1,3,4    ]]

array([11, 13, 14])

In [148]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [149]:
A[1,2]

15

## **Slicing**


In [151]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [153]:
a[1:4]

array([11, 12, 13])

In [155]:
a[1:5:2]

array([11, 13])

In [161]:
a[::2]

array([10, 12, 14])

In [162]:
a[:5:2]

array([10, 12, 14])

In [163]:
a[:5:]

array([10, 11, 12, 13, 14])

In [165]:
b = np.arange(10,31)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [160]:
b[1:14:2]

array([11, 13, 15, 17, 19, 21, 23])

In [170]:
b[:21:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [172]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [176]:
A[0,:]

array([10, 11, 12])

In [177]:
A[:, 0]

array([10, 13, 16])

In [181]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [185]:
A[[0,2], 0:2]

array([[10, 11],
       [16, 17]])

## **Condicionales y arreglos Booleanos**

In [187]:
A = np.random.random((4,4))
A 

array([[0.30698011, 0.14756692, 0.79153406, 0.12586291],
       [0.94688479, 0.43242557, 0.61122538, 0.20416666],
       [0.29979391, 0.07552054, 0.79014082, 0.95572772],
       [0.71661707, 0.95015562, 0.78074356, 0.22200263]])

In [188]:
A>0.5

array([[False, False,  True, False],
       [ True, False,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True, False]])

In [191]:
A[A>0.5]

array([0.79153406, 0.94688479, 0.61122538, 0.79014082, 0.95572772,
       0.71661707, 0.95015562, 0.78074356])

# **Pandas**

pandas es una biblioteca de Python de código abierto para análisis de datos altamente especializados. Actualmente es el punto de referencia que todos los profesionales que utilizan el lenguaje Python deben estudiar con fines estadísticos de análisis y toma de decisiones.

In [192]:
import pandas as pd 

In [194]:
s = pd.Series([12, -4, 7,9])
s

0    12
1    -4
2     7
3     9
dtype: int64

In [196]:
s = pd.Series([12, -4, 7,9], index= ['a', 'b', 'c', 'd'])
s


a    12
b    -4
c     7
d     9
dtype: int64

# **Referencias**

[1]. https://es.wikipedia.org/wiki/NumPy 

[2]. Unpingo J. Python for Probability, Statistics and Machine Learning. Second Edition. Ed. 
Springer